const projectData = [
  {
    id: 1,
    propertyName: 'MGP Joyous',
    location: 'PERUNGUDI',
    returns: 9,
    minInvestment: 500000,
    period: '6 Months',
    totalCost: 70000000,
  },
  {
    id: 2,
    propertyName: 'MGP Verdant',
    location: 'PALLIKARANAI',
    returns: 18,
    minInvestment: 500000,
    period: '6 Months',
    totalCost: 250000000,
  },
  {
    id: 3,
    propertyName: 'MGP Uprise',
    location: 'Kandhanchavadi',
    returns: 9,
    minInvestment: 500000,
    period: '6 Months',
    totalCost: 15000000,
  },
  {
    id: 4,
    propertyName: 'MGP Joyous',
    location: 'PERUNGUDI',
    returns: 9,
    minInvestment: 500000,
    period: '6 Months',
    totalCost: 70000000,
  },
  {
    id: 5,
    propertyName: 'MGP Commercial Plot',
    location: 'VELACHERY',
    returns: 9,
    minInvestment: 500000,
    period: '6 Months',
    totalCost: 20000000,
  },
  {
    id: 6,
    propertyName: 'MGP Kings Park',
    location: 'Thazhambur',
    returns: 9,
    minInvestment: 500000,
    period: '6 Months',
    totalCost: 50000000,
  },
  {
    id: 7,
    propertyName: 'MGP Sriya',
    location: 'Sholinganallur',
    returns: 18,
    minInvestment: 500000,
    period: '6 Months',
    totalCost: 45000000,
  },
]

export default projectData
